### ISSUE TITLE
403: forbidden (access denied) error on certain tracks

### ISSUE THREAD

**Issue by mcprat** [erwinkramer/SoundCloud-Playlist-Sync#10]
Screenshot:

![i17 cimgpsh_orig](https://cloud.githubusercontent.com/assets/10858067/20491649/08f1edb8-afe0-11e6-995d-886706a1ab7b.png)

This only happens when attempting the last 4 tracks and it's the same tracks every time (used to be 2 but I added 2 more that cause the same incident).

I don't expect this to be fixed as it is very strange...but at least I would like to know what those tracks are so I can unlike and download manually or other.

It would be enough for me if the manifest can generate the track IDs of tracks that have NOT been downloaded successfully, both for this and other future problems (or maybe even generate a different file like error.log or whatever). Then, we can even see which tracks cause this and then use them for testing, etc.

Thanks

**Comment by erwinkramer** [comment]
Fixed with more information being displayed. Commit: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/commit/5756f8fa8846344ce14a21bf6f82bc0358251f0f

This also writes exceptions to the Windows Event Log
