### ISSUE TITLE
Unable to download any of my playlists

### ISSUE THREAD

**Issue by noisysongbird** [erwinkramer/SoundCloud-Playlist-Sync#11]
Hey, I spoke with you before about an issue that occurred when trying to download my playlists and we came to the conclusion that I needed to use the API link to download tracks from my playlists.  

In the new SoundCloud update, they removed the embedded link from playlist sharing so there is no way for me to download playlists using your app.  

Do you happen to know what I need to change on my profile for URL's to work or do you know another way to pull the API link?

**Comment by erwinkramer** [comment]
Not sure what the new update is you are talking about, i don't notice any changes. Can you check if you can get the playlist ID with something like this http://blog.soundsgood.co/how-to-find-a-soundcloud-playlist-id/ ? Could you also provide a playlist you are testing with?

**Comment by noisysongbird** [comment]
this is the playlist: https://soundcloud.com/noisysongbird/sets/sounds-of-the-forest-2017

if you're on a desktop and try to share it, you will see that the tab for "embedded" is no longer there but the site that you provided should work because all I need is the playlist ID.

**Comment by erwinkramer** [comment]
Yeah it returns a playlist ID so i guess you're good for now?

I see the problem, not really a nice update from Soundcloud...

**Comment by noisysongbird** [comment]
Pretty typical from them.  This will work for now and I can close the issue but do you happen to have any idea as to what is preventing me from using the playlist URL in the app as opposed to the playlist ID?

**Comment by erwinkramer** [comment]
If I'm not mistaken then the way to fix this is to create some workaround. Maybe i need to that since more people will bump in this soon...

**Comment by erwinkramer** [comment]
Oh and @noisysongbird just keep this issue open so i remember to do this :)

**Comment by noisysongbird** [comment]
It feels like the issue is coming stemming from my profile because the issue doesn't occur with a certain playlist, none of them will work for me and I've had friends try downloading my playlists with their downloaders that they have made but even those wont work.

I used to be able to use downloaders with my playlist URL just fine but one day it randomly stopped working.  My only guess is that it had something to do with having a soundcloud GO account but I dont really know how that would prevent my playlists from downloading

**Comment by erwinkramer** [comment]
@noisysongbird 
I created an extra way to find the playlist ID with commit: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/commit/6a8f11926070b6d501878d0ae950395f0d0f6407 . 

If it fails to get the playlist ID with the API it now searches the HTML webpage and attempts to find a tag which includes the playlist ID.

If you update the app it will work.
