### ISSUE TITLE
Re-download required after moving files in a different sub-folder

### ISSUE THREAD

**Issue by rtomasello** [erwinkramer/SoundCloud-Playlist-Sync#12]
I've re-downloaded all song in my personal playlist - more than 5,800 files- following the release of the latest version 2.10.1 as this is incompatible with previous versions. However, after I moved these files in a different sub-folder the software requires to download my entire playlist once again as it doesn't recognize the old files in the sub-folder.

**Comment by erwinkramer** [comment]
Did you also move the manifest file to the new sub-folder and pointed the app local directory to the new sub-folder as well? 

Could you please provide the following: 
- a screenshot of your current settings in the app
- the filepath of the JSON (manifest) file.
- the filename of the JSON file.

**Comment by rtomasello** [comment]
![capture](https://cloud.githubusercontent.com/assets/24699269/21395118/31327886-c793-11e6-81a5-7afd4e2c0fe4.PNG)

**Comment by rtomasello** [comment]
[MNFST=soundcloud.com_rickscafe_likes,FPA=True,IAIF=True,DM=Favorites,SM=1.txt](https://github.com/erwinkramer/SoundCloud-Playlist-Sync/files/666735/MNFST.soundcloud.com_rickscafe_likes.FPA.True.IAIF.True.DM.Favorites.SM.1.txt)

**Comment by rtomasello** [comment]
[MNFST=soundcloud.com_rickscafe_likes,FPA=True,IAIF=True,DM=Favorites,SM=1.txt](https://github.com/erwinkramer/SoundCloud-Playlist-Sync/files/666755/MNFST.soundcloud.com_rickscafe_likes.FPA.True.IAIF.True.DM.Favorites.SM.1.txt)

**Comment by erwinkramer** [comment]
After a talk on Gitter we came to the conclusion that the 'sort songs into folders by artist' checkbox should have been enabled. The check on the 'sort songs into folders by artist' checkbox should have raised a cancellation. Needs to be figured out why, in this scenario, it didn't work.

**Comment by erwinkramer** [comment]
the tool works with relative paths and no further issues are known when renaming or moving the sync folder,
