### ISSUE TITLE
Unauthorised Error

### ISSUE THREAD

**Issue by jamespcnut** [erwinkramer/SoundCloud-Playlist-Sync#13]
When trying to synchronise the program attempts to run and then an error pop up appears saying:
![image](https://cloud.githubusercontent.com/assets/25700208/22851072/683f8570-f06b-11e6-998b-1228a35431e8.png)

The soundcloud API is not down and changing the playlist or artists tracks I am trying to download does not resolve the issue

**Comment by mcprat** [comment]
Yeah...app is broken right now...we'll get back to you when we find a resolution

**Comment by erwinkramer** [comment]
@jamespcnut It still works for me, could you double check:
- The version you are using, it should be 2.10.1.20
- The tab Client ID should have a current client ID starting with 93a (same as stock client ID)

This is however is an old client ID, i reverted back to this older client ID because the newer one stopped working and returned the unauthorized like you got, we should need a new client ID by filling a form [here ](http://soundcloud.com/you/apps/new) and hoping they will accept. However i can't mention it's for this app for obvious reasons ;)

**Comment by erwinkramer** [comment]
@jamespcnut  I just see from looking at your error message that you are using the client id in a previous version of the app, please click on the update button on the top.

**Comment by erwinkramer** [comment]
I just found another client id that i will also include on the app, so we end up with 2 working client IDs

**Comment by jamespcnut** [comment]
Yes i'm running 2.10.1.20, and the client id begins with 93a.
I have hit update and it says there are no updates available, I have also reinstalled the program.

**Comment by jamespcnut** [comment]
The error I uploaded was with an alternative client id that I had found that must have also stopped working. Having reverted back to the default id the error still remains.

**Comment by erwinkramer** [comment]
@jamespcnut  so the cliend id is also different IN the same error you are getting?

**Comment by jamespcnut** [comment]
Yes when I changed it back to the default id then the error showed the default id at the end of the api address. Upon looking at the source of the other id I used, their id stopped working months ago for whatever they were using it for. I just used it to confirm it was an id error

**Comment by erwinkramer** [comment]
I've added a new default client id with a new update ready to download, please let me know if the problem still persists.

**Comment by jamespcnut** [comment]
The error still persists but only when trying to download all tracks off of an artists page. The program can download a playlist without any problems.

**Comment by jamespcnut** [comment]
From further testing it seems to be a user id resolve issue. If instead of the users address I put in soundcloud.com/[user_id] then it attempts to download their tracks but throws a new error.
![image](https://cloud.githubusercontent.com/assets/25700208/22870662/65b84498-f1fd-11e6-8cb4-6e8f29b17c70.png)

**Comment by erwinkramer** [comment]
@jamespcnut  that points to something different. What user are you trying to get tracks from? 

To resolve the event log issue:
- Run your application once as an administrator
- Rerun the sync on the user where you get the errors

Please post the outcome and new errors you get.

**Comment by tobias231h** [comment]
I got the same error when trying to download tracks from artist url. (404 - Not found)
I could solve the issue when replacing the username with the user id.
Here you can lookup the user id:
https://helgesverre.com/soundcloud/

**Comment by tobias231h** [comment]
@jamespcnut I solved the issue by unticking 'Choose high quality versions if availiable'.
It seems that https://api.soundcloud.com/tracks/xxxxxx/download?client_id=XXX is not working even if the program detects, that the song is available in "high quality"

**Comment by erwinkramer** [comment]
@tobias231h I updated the app so it gets the artist ID first before it tries to get the tracks from the artist. Please update the app and try it out. 

If you want to chat with me you can do so at https://gitter.im/erwinkramer/SoundCloud-Playlist-Sync

**Comment by erwinkramer** [comment]
2 bugfixes done. I guess it's solved now.
