### ISSUE TITLE
Unable to get MD5 checksum for the key file "Soundcloud Playlist Downloader_TemporaryKey.pfx

### ISSUE THREAD

**Issue by tinnetju** [erwinkramer/SoundCloud-Playlist-Sync#15]
Hi, first of all I would like to thank you for keeping this amazing piece of software up-to-date, it's the best (and possibly the only public) Soundcloud downloader there is at the moment.

I downloaded the entire solution as I am trying to build in Visual Studio, however I am getting the following error which was not an issue in the previous version(s)

Unable to get MD5 checksum for the key file "Soundcloud Playlist Downloader_TemporaryKey.pfx". Could not find file 'C:\....\SoundCloud-Playlist-Sync-fix\Soundcloud Playlist Downloader\Soundcloud Playlist Downloader_TemporaryKey.pfx'.	Soundcloud Playlist Downloader			

I Googled and Microsoft.net said this could be solved by adding 'bypassTrustedAppStrongNames enabled="false' to the configuration file but I'm having no luck. Could you please look into this as I am unable to run the application at the moment.

**Comment by erwinkramer** [comment]
Maybe use your own signing key in the project properties?

**Comment by tinnetju** [comment]
I don't have a signing key, and I can't just turn it off apparently as it says 'no license key installed'. 

Sorry if this is common sense but I never had to deal with signing keys before

**Comment by erwinkramer** [comment]
Yea I had this stuff to make use of clickonce from Microsoft. I'll look into it another time to see if I can ease some security.

**Comment by tinnetju** [comment]
That would be awesome, thank you. 

Do you know of some temporary fix in the meantime or is there a different way to obtain the current up-to-date .exe?

**Comment by mcprat** [comment]
Just grab the latest release and let it update itself on run

https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/download/r2.10.1.7/Soundcloud.Playlist.Sync_2_10_1_7.zip

**Comment by tinnetju** [comment]
Alright, got it. Thanks so much!

**Comment by tinnetju** [comment]
It doesn't seem to be updating on startup, and I'm getting the 'Soundcloud API seems to be down' error

**Comment by mcprat** [comment]
Make sure any antivirus isn't blocking anything. You may have to start it more than once...

Otherwise just keep trying to sync it should work eventually...or you can try to change the client ID.

**Comment by erwinkramer** [comment]
Hi @tinnetju ,

Create your own Test Certificate, or choose to not sign it at the Signing tab of the project:
![image](https://cloud.githubusercontent.com/assets/4255748/23803785/e37e387e-05b7-11e7-8ddb-3fbc63c22007.png)
