### ISSUE TITLE
doesn't download correct metadata

### ISSUE THREAD

**Issue by Hammad1029** [erwinkramer/SoundCloud-Playlist-Sync#16]
The program doesn't download the correct metadata. The artist name is saved as who ever is the uploader and not from the metadata that most uploaders(monstercat in my case) provides. The title is also the upload title and not from the metadata and same also goes with the genre and the album name. The program is otherwise great! It would be great if you could fix this

**Comment by erwinkramer** [comment]
Hi @Hammad1029,

Consider this track: https://soundcloud.com/monstercat/gareth-emery-standerwick-saving-light?in=monstercat/sets/monstercat-030-finale

The info i got for this track is below, as you can see the artist name is embedded in the `"title" `element, i could do parsing on strings to 'guess' the artist name, but i wouldn't consider that reliable.
`{
	"kind": "track",
	"id": 305283195,
	"created_at": "2017/01/30 18:58:08 +0000",
	"user_id": 8553751,
	"duration": 275748,
	"commentable": true,
	"state": "finished",
	"original_content_size": 97247972,
	"last_modified": "2017/03/04 23:42:42 +0000",
	"sharing": "public",
	"tag_list": "\"Gareth Emery\" Standerwick HALIENE \"Saving Light\" EDM Electronic \"Dance Music\" Melodic Monstercat",
	"permalink": "gareth-emery-standerwick-saving-light",
	"streamable": true,
	"embeddable_by": "all",
	"purchase_url": "https://Monstercat.lnk.to/SavingLight",
	"purchase_title": "🎧 Stream / Download",
	"label_id": null,
	"genre": "Trance",
	"title": "Gareth Emery & Standerwick - Saving Light (feat. HALIENE)",
	"description": "🎧 Support on all platforms: https://Monstercat.lnk.to/SavingLight\n\nWhether you need help, or would like to help someone else, it can start with a conversation. #SavingLight is our chance to stand together to spread the word on positivity and love. All of the proceeds from February will be donated to Ditch the Label: https://www.monstercat.com/savinglight\n\n💥 Follow Gareth Emery:\nFacebook: https://www.facebook.com/garethemery\nTwitter: http://twitter.com/garethemery\nInstagram: http://instagram.com/garethemery\nYouTube: http://youtube.com/officialgarethemery\n\n💥 Follow Standerwick:\nFacebook: www.facebook.com/standerwickmusic\nTwitter: www.twitter.com/ianstanderwick\nSoundCloud: www.soundcloud.com/standerwick\nInstagram: www.instagram.com/standerwick.dj\n\n💥 Follow HALIENE\nInstagram: https://www.instagram.com/halienemusic/\nFacebook: https://www.facebook.com/haliene/\nTwitter: https://twitter.com/halienemusic\nSoundCloud: https://soundcloud.com/halienemusic\n\n😺 Follow Monstercat\nSnapchat: https://www.snapchat.com/add/monstercat\nYouTube: http://www.youtube.com/Monstercat\nSpotify: http://monster.cat/1hGrCWk\nFacebook: http://facebook.com/Monstercat\nTwitter: http://twitter.com/Monstercat\nInstagram: http://instagram.com/monstercat\nVine: https://vine.co/monstercat\nSoundCloud: http://soundcloud.com/Monstercat\nGoogle+: https://plus.google.com/+Monstercat\nMonstercat FM: http://live.monstercat.com\n\n🎵 Genre: Trance\n\n👕 Want some new Merchandise?\nhttp://monster.cat/MonstercatShop",
	"label_name": "Monstercat",
	"release": null,
	"track_type": null,
	"key_signature": null,
	"isrc": null,
	"video_url": null,
	"bpm": null,
	"release_year": 2017,
	"release_month": 1,
	"release_day": 30,
	"original_format": "wav",
	"license": "all-rights-reserved",
	"uri": "https://api.soundcloud.com/tracks/305283195",
	"user": {
		"id": 8553751,
		"kind": "user",
		"permalink": "monstercat",
		"username": "Monstercat",
		"last_modified": "2017/02/23 19:40:10 +0000",
		"uri": "https://api.soundcloud.com/users/8553751",
		"permalink_url": "http://soundcloud.com/monstercat",
		"avatar_url": "https://i1.sndcdn.com/avatars-000296522545-0me7o3-large.jpg"
	},
	"permalink_url": "https://soundcloud.com/monstercat/gareth-emery-standerwick-saving-light",
	"artwork_url": "https://i1.sndcdn.com/artworks-000205461132-0vwtvq-large.jpg",
	"stream_url": "https://api.soundcloud.com/tracks/305283195/stream",
	"download_url": "https://api.soundcloud.com/tracks/305283195/download",
	"playback_count": 558560,
	"download_count": 0,
	"favoritings_count": 20871,
	"reposts_count": 3938,
	"comment_count": 397,
	"downloadable": false,
	"waveform_url": "https://w1.sndcdn.com/VPJq4Ediump6_m.png",
	"attachments_uri": "https://api.soundcloud.com/tracks/305283195/attachments"
}`

**Comment by Hammad1029** [comment]
If by that you mean that in the title element, there is the wrong name, its not like that. The track you used is a collection of songs in a single track but if you use a single song like for e.g. https://soundcloud.com/monstercat/unlike-pluto-everything-black it wont happen probably(if I understand what you're saying)

**Comment by erwinkramer** [comment]
@Hammad1029  hi,

For your new example it's still the same issue. The response below is all that i can work with. As you can see the artist:

> Unlike Pluto

Is only in the `Title`, `Description `and `Tag_list` elements.

`{
	"kind": "track",
	"id": 311732223,
	"created_at": "2017/03/10 18:37:42 +0000",
	"user_id": 8553751,
	"duration": 229062,
	"commentable": true,
	"state": "finished",
	"original_content_size": 40395932,
	"last_modified": "2017/03/10 18:40:33 +0000",
	"sharing": "public",
	"tag_list": "Monstercat Melodic \"Unlike Pluto\" \"Everything Black\" \"Mike Taylor\" EDM Electronic Dance Music Bass",
	"permalink": "unlike-pluto-everything-black",
	"streamable": true,
	"embeddable_by": "all",
	"purchase_url": "https://Monstercat.lnk.to/EverythingBlack",
	"purchase_title": "?? Stream / Download",
	"label_id": null,
	"genre": "Electronic",
	"title": "Unlike Pluto - Everything Black (feat. Mike Taylor)",
	"description": "??  Support on all platforms:\nhttps://Monstercat.lnk.to/EverythingBlack\n\n?? Snapchat: https://www.snapchat.com/add/monstercat\n\n??  Follow Monstercat\nSnapchat: https://www.snapchat.com/add/monstercat\nYouTube: http://www.youtube.com/Monstercat\nSpotify: http://monster.cat/1hGrCWk\nFacebook: http://facebook.com/Monstercat\nTwitter: http://twitter.com/Monstercat\nInstagram: http://instagram.com/monstercat\nVine: https://vine.co/monstercat\nSoundCloud: http://soundcloud.com/Monstercat\nGoogle+: https://plus.google.com/+Monstercat\nMonstercat FM: http://live.monstercat.com\n\n?? Follow Unlike Pluto\nFacebook: https://www.facebook.com/unlikepluto\nTwitter: https://twitter.com/unlikepluto\nSoundcloud: https://soundcloud.com/unlikepluto\nInstagram: https://www.instagram.com/unlikepluto\n\n?? Follow Mike Taylor\nFacebook: https://www.facebook.com/iammiketaylor\nTwitter: https://twitter.com/iammiketaylor\nSoundcloud: https://soundcloud.com/iammiketaylor\nInstagram: https://www.instagram.com/iammiketaylor\n\n??  Genre: Electronic\n\n?? Want some new Merchandise?\nhttp://monster.cat/MonstercatShop",
	"label_name": "Monstercat",
	"release": null,
	"track_type": null,
	"key_signature": null,
	"isrc": "CA6D21700049",
	"video_url": null,
	"bpm": null,
	"release_year": 2017,
	"release_month": 3,
	"release_day": 10,
	"original_format": "wav",
	"license": "all-rights-reserved",
	"uri": "https://api.soundcloud.com/tracks/311732223",
	"user": {
		"id": 8553751,
		"kind": "user",
		"permalink": "monstercat",
		"username": "Monstercat",
		"last_modified": "2017/02/23 19:40:10 +0000",
		"uri": "https://api.soundcloud.com/users/8553751",
		"permalink_url": "http://soundcloud.com/monstercat",
		"avatar_url": "https://i1.sndcdn.com/avatars-000296522545-0me7o3-large.jpg"
	},
	"permalink_url": "https://soundcloud.com/monstercat/unlike-pluto-everything-black",
	"artwork_url": "https://i1.sndcdn.com/artworks-000211938208-pjm5h5-large.jpg",
	"stream_url": "https://api.soundcloud.com/tracks/311732223/stream",
	"download_url": "https://api.soundcloud.com/tracks/311732223/download",
	"playback_count": 22659,
	"download_count": 0,
	"favoritings_count": 3067,
	"reposts_count": 631,
	"comment_count": 48,
	"downloadable": false,
	"waveform_url": "https://w1.sndcdn.com/Ecp52LaOKEjq_m.png",
	"attachments_uri": "https://api.soundcloud.com/tracks/311732223/attachments"
}
`

**Comment by Hammad1029** [comment]
but then can't you pull it from the tag list elements? if its unreliable but can work, can you please add an option to select it?

**Comment by erwinkramer** [comment]
@Hammad1029 , in your case, every song has a tag list that always starts with the artist name? If so, i could do that. You see it's unreliable because it's totally up to the uploader to decide how to structure that sort of thing, because the soundcloud API doesn't feature it.

**Comment by Hammad1029** [comment]
I'd like if you'd add it. Because in the case of most professional uploaders(like labels - in my case monstercat) they do do it correctly

**Comment by erwinkramer** [comment]
@Hammad1029 ,

I'm sorry, i think this one is too specific.
