### ISSUE TITLE
Exception while downloading track (The operation was canceled / AggregateInnerException)

### ISSUE THREAD

**Issue by mistertoze** [erwinkramer/SoundCloud-Playlist-Sync#19]
Hi there,

I recall having a similar issue with the other version.
Songs would fail to download, but the downloader would skip them until reaching the end, and then present a list of song names that failed.

Sadly this version stops immediately once a song fails.
To sidestep this, it's necessary to increase the amount of concurrency above the number of songs that fail, and keep accepting the error and starting the sync again.

I was testing this further right now, and it seems that whatever track info the downloader is looking at is outdated, because I looked at these playlists and there are songs missing.

One of the playlists says it has 499 songs but 5 of them are missing, which are exactly the ones that the downloader fails to fetch.

I guess there's not recovering those songs, so the only thing that's not ideal is the downloader failing immediately instead of skipping the song and showing the list of errors at the end.

Cheers.

**Comment by erwinkramer** [comment]
Hi @mistertoze ,

Sorry for the late response. I updated the app to only cancel the sync if there are 10 or more songs failing.

To further investigate your issue with songs missing from the playlist, can you provide the playlist URL and the songs that are missing?

**Comment by RoboMWM** [comment]
Yea, it'd be nice if the application could just skip over ones it fails to download, and present a list of them afterwards instead of just canceling the entire operation. There's no need for some arbitrary threshold that causes the entire process to abort.

**Comment by erwinkramer** [comment]
@RoboMWM  So if there is a critical issue that causes every single track to fail, in lets say a playlist of 1000 tracks, do you want it to go over all those 1000?

**Comment by RoboMWM** [comment]
Playlists can only go to a max of 500 songs, but yes, it should, and then report the ones that fail. If all of them are failing, I'm sure most users would see this... but anyways, I discovered that more recent versions exist in the repo that aren't in releases, so I used that and was able to successfully download a playlist.

**Comment by erwinkramer** [comment]
Didn't you get notified to update during startup of the app?

**Comment by RoboMWM** [comment]
No, but clicking update caused it to hang shortly after a message prompt saying it would restart or something. Restarting the app still seemed to use the old version.

**Comment by Hammad1029** [comment]
Same problem here, It's really annoying

**Comment by RoboMWM** [comment]
@Hammad1029 Are you using 3.0.0.32? It seems that version doesn't just flat out abort on the first failed track (and also seems to fix issues with failures in the first place).

Also, re the hypothetical - that would be a rare occurrence, and even if that were the case, I'd like the program to get as much as it can anyways.

**Comment by mcprat** [comment]
3.0.0.32 is the latest build that all of you should be trying before you tell Erwin to change anything.

If you are having trouble updating, uninstall the program (like you would do any other program, via the Control Panel) and remove the folder located at C:\Users\<User>\AppData\Local\Apps\2.0 then redownload the most recent release here on Github. Make sure Windows SmartScreen or your Antivirus doesn't block anything.

Let us know how it goes.

**Comment by erwinkramer** [comment]
Hi @mistertoze , @RoboMWM  and @Hammad1029 ,

Exception handling has been improved again. It will write the exceptions (per track) to a logfile in the same folder as your manifest. Also the display message is improved. If you experience issues with this new progress, please open a new issue with detailed information.
