### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Hammad1029** [erwinkramer/SoundCloud-Playlist-Sync#21]
It was working perfectly until a week or so before when the app wouldn't start and since then reinstalling doesn't work either. It just says "Application cannot be started. Contact the application vendor." and gives a log file of which I've pasted the content below. BTW, I'm on windows 7 ultimate with a core 2 duo e8400@3ghz and 3gb of ddr2 ram with no graphics car; this probably won't be useful, but eh. Thanks in advance :) .

`
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1590.0 built by: NETFXREL2
	clr.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/raw/fix/Deployment/Soundcloud%20Playlist%20Sync.application
	Deployment Provider url		: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/raw/fix/Deployment/Soundcloud%20Playlist%20Sync.application
	Application url			: https://raw.githubusercontent.com/erwinkramer/SoundCloud-Playlist-Sync/fix/Deployment/Application%20Files/Soundcloud%20Playlist%20Sync_3_0_0_31/Soundcloud%20Playlist%20Sync.exe.manifest

IDENTITIES
	Deployment Identity		: Soundcloud Playlist Sync.application, Version=3.0.0.31, Culture=en, PublicKeyToken=61d8ca1b5d5ee862, processorArchitecture=msil
	Application Identity		: Soundcloud Playlist Sync.exe, Version=3.0.0.31, Culture=en, PublicKeyToken=61d8ca1b5d5ee862, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://github.com/erwinkramer/SoundCloud-Playlist-Sync/raw/fix/Deployment/Soundcloud%20Playlist%20Sync.application resulted in exception. Following failure messages were detected:
		+ The application binding data format is invalid. (Exception from HRESULT: 0x800736B2)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [7/6/2017 12:20:43 AM] : Activation of https://github.com/erwinkramer/SoundCloud-Playlist-Sync/raw/fix/Deployment/Soundcloud%20Playlist%20Sync.application has started.
	* [7/6/2017 12:20:45 AM] : Processing of deployment manifest has successfully completed.
	* [7/6/2017 12:20:45 AM] : Installation of the application has started.
	* [7/6/2017 12:20:45 AM] : Processing of application manifest has successfully completed.
	* [7/6/2017 12:20:48 AM] : Found compatible runtime version 4.0.30319.
	* [7/6/2017 12:20:48 AM] : Request of trust and detection of platform is complete.
	* [7/6/2017 12:21:01 AM] : Downloading of subscription dependencies is complete.
	* [7/6/2017 12:21:01 AM] : Commit of the downloaded application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [7/6/2017 12:21:01 AM] System.Runtime.InteropServices.COMException
		- The application binding data format is invalid. (Exception from HRESULT: 0x800736B2)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IEnumSTORE_ASSEMBLY.Next(UInt32 celt, STORE_ASSEMBLY[] rgelt)
			at System.Deployment.Internal.Isolation.StoreAssemblyEnumeration.MoveNext()
			at System.Deployment.Application.ComponentStore.CollectCrossGroupApplications(Uri codebaseUri, DefinitionIdentity deploymentIdentity, Boolean& identityGroupFound, Boolean& locationGroupFound, String& identityGroupProductName)
			at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by erwinkramer** [comment]
This is a ClickOnce issue i guess. Can you follow these instructions with someone having similar problems with an other app and check if it helps? 
https://care.citrixonline.com/openvoice/troubleshooting/error-the-application-binding-data-format-is-invalid-exception-from-hresult-0x800736b2-during-installation-of-outlook-plugin-000357116

**Comment by erwinkramer** [comment]
Make sure you have the sync tool closed and close all other apps if you can't remove the folder as instructed. After that the app will redownload itself.

**Comment by Hammad1029** [comment]
Thanks for the early reply. It's working now, you can close this issue now. :)
