### ISSUE TITLE
preview songs 

### ISSUE THREAD

**Issue by Hammad1029** [erwinkramer/SoundCloud-Playlist-Sync#23]
Can you have a workaround for only-preview and country-blocked songs? maybe like how 4kdownload does it, they parse the link themselves and then the user downloads it via their own network

**Comment by mcprat** [comment]
This would be against their Terms of Service for apps I'm pretty sure...

For individual tracks that are country-blocked, does http://peggo.tv work?

**Comment by erwinkramer** [comment]
>the user downloads it via their own network

There is no network behind the app. If that is what you think. Everything is done by your own connection. If you want it centralized I don't think I can help with that. A work around is simply to connect with a VPN from a country without blocks and run the app for those tracks.

**Comment by Hammad1029** [comment]
Yeah but 4kdownload does it fine. The reason why I don't use it is that your program is solely meant to sync and gives much better file format along with tags and is much better overall

**Comment by erwinkramer** [comment]
@Hammad1029 ,

I have no interest in building this 'feature' in, unless you know a trick (technical) to make it recognize it from another country. I'm not building a VPN solution in this app.
