### ISSUE TITLE
Download multiple playlists 

### ISSUE THREAD

**Issue by Hammad1029** [erwinkramer/SoundCloud-Playlist-Sync#24]
Okay, so unlike my other shit, this one might actually be doable and I think you'd want to. My playlist on soundcloud just reached 500 and as you may know, that is actually the limit on soundcloud. So making another playlist and syncing that and old one both everytime is just a hassle. Can you add a feature for multiple playlists? as in you enter two links and when it's done with the first it'll do the second. Thanks.

**Comment by mcprat** [comment]
Sure why not

Alternatively, you could just like all the tracks across playlists, or just like them instead of putting them in playlists at all. If you have experience with Python, you can make SC playlists in bulk using groups of track IDs after downloading.

**Comment by Hammad1029** [comment]
liking them all is a just hassle plus I have devices that I don't download the songs on so I stream them on soundcloud and streaming liked songs takes away much of the functionality that normal playlists have. And I don't have experience with python, just with C and a bit of C++, tho Python is on my list to learn :)

**Comment by mcprat** [comment]
You must have a lot of playlists lol

Just curious, what is more important to you, maintaining separate playlists on SC, or just getting your tracks downloaded? Or you want all of your tracks to be split up the same way they are online, in playlist folders?

**Comment by Hammad1029** [comment]
I have 504 songs currently, split into two playlists of one containing 500 and the other with 4. I just want 2 (or more depending on how many songs I keep discovering) main playlists on soundcloud that I can download from just the way I did before and keep on listening online on devices I don't have me downloaded. Nothing fancy like playlists for individual playlists for artists.

**Comment by Hammad1029** [comment]
@erwinkramer

**Comment by Hammad1029** [comment]
@erwinkramer help

**Comment by mcprat** [comment]
There's not much I can do to help but here's another suggestion...
You don't have many playlists right? So what about opening multiple instances with Shift + Click?

https://www.digitalcitizen.life/how-quickly-open-multiple-windows-same-application

**Comment by erwinkramer** [comment]
This is a little tricky to implement because it's probably not going to be backwards compatible then.

**Comment by mcprat** [comment]
@Hammad1029 you want the playlists to remain split up when downloaded or no?

**Comment by erwinkramer** [comment]
@Hammad1029  if you have multiple personal playlists in your account you can now download them  with the new download method "All playlists from this user URL", which is made possible by the addition from  @valentingiraud !

**Comment by erwinkramer** [comment]
@Hammad1029 and @mpratt14 ,

I made another new version (3d24e6221057ca7f475229b57bfaed381b989519), here you can make up to 5 different configurations.
