### ISSUE TITLE
different sc playlists ending up on multiple folders 

### ISSUE THREAD

**Issue by Hammad1029** [erwinkramer/SoundCloud-Playlist-Sync#26]
I started using your new multiple playlists feature and it's working perfectly but has one problem. The program makes different folders for the different playlists on SC which makes it difficult to sort songs as I sync my music to Google Drive. Can there be an option to check that whether or not SC playlists get merged into one folder or not.

**Comment by erwinkramer** [comment]
Added in 154f8b5bc39565f57309cb961bfb969fc27f97a1, you can now update to the new version.
