### ISSUE TITLE
Help: "Change settings or directory"

### ISSUE THREAD

**Issue by rmvz** [erwinkramer/SoundCloud-Playlist-Sync#27]
I keep getting stuck on the same error message stating "Change settings or directory". This happens everytime I uncheck the "include artist name in filename" option which is automatically checked when I start the program. The only way for the program to work is by checking this option again. I've tried changing directories, uninstalling the program and even older versions but I keep getting this message. All I want is to not use that option anymore, but it just won't let me for some reason. Is this a fault or am I just doing something wrong?

**Comment by erwinkramer** [comment]
It's based on your local directory, in that folder a manifest file is placed based on the settings you initially used on that directory. Try an empty folder and tell me how that goes.

**Comment by erwinkramer** [comment]
Also; every option, including  "include artist name in filename", will persist when a synchronization is successfully started or when you switch configs.

**Comment by rmvz** [comment]
I changed the local directory to a different folder and it worked. Though does this mean that you can't use the same directory when changing settings as this seems to have created that error message, right? I actually deleted that manifest file and it does again let me download to the previous directory I was using, but I don't know if this does any harm. 

Also, there is a small typo in the error message I only now see, it says "directoy" instead of "directory".

**Comment by erwinkramer** [comment]
> Though does this mean that you can't use the same directory when changing settings as this seems to have created that error message, right?

You can, using the way you described, but that also means the program now doesn't know the difference of what it has downloaded previously, and what is changed locally.

Keeping the settings the way they are seems to be the most simple approach to support actual synchronization.

**Comment by erwinkramer** [comment]
Oh and thanks for noting the typo, i fixed that now and you can get it from updating the app now! 👍

**Comment by rmvz** [comment]
But changing the settings then actually requires picking a new directory as well, right? But won't the program then also not know what it has downloaded previously and what it hasn't, basically downloading everything again?

**Comment by erwinkramer** [comment]
> But changing the settings then actually requires picking a new directory as well, right? 

yes

> But won't the program then also not know what it has downloaded previously and what it hasn't, basically downloading everything again?

The content of the manifest file is all the program 'knows', just open it in notepad and check what it knows. There is no other storage by the app, except the settings it stores in the install folder.

**Comment by rmvz** [comment]
I don't know whether I understand it correctly or not. Say I change my mind on something and I'd like to change the settings again, I would have to pick another directory and the program will download thousands of songs that I already have again? Everytime I change the settings? Maybe I'm wrong, please correct me if so, because I have no idea how this is programmed, but that doesn't sound very ideal.

**Comment by erwinkramer** [comment]
> I would have to pick another directory and the program will download thousands of songs that I already have again? Everytime I change the settings? 

Yes, but u could have multiple folders with different configs, so for each type of setting you want, you can make a different folder. You've seen the config feature in the application, right?

> but that doesn't sound very ideal.

Maybe not for you, but i had in mind that settings would not change very often. I did however had in mind that track metadata or even the track itself could change on SoundCloud, it's comparing the downloaded one with the live one and getting the updated one (if there is an update) every time you sync (a feature i haven't seen in much in media download applications, by the way).

**Comment by rmvz** [comment]
> You've seen the config feature in the application, right?

I have indeed. I'll try work with it and see from there how I'll organize my music.

> a feature i haven't seen in much in media download applications, by the way

That sure is a nice feature indeed. Thanks for taking the time to reply and helping me out :)

**Comment by mcprat** [comment]
@rmvz Remember that you can manipulate the contents of the manifest file to not get duplicates of what you have downloaded from the other directory already if you want...

Just take lines from the original and put it in the new one, or, you can figure out the real difference between the manifests with different settings by the differences in the filename and just make a copy of the original manifest into another directory and change the filename to match the settings you want to use there.
