### ISSUE TITLE
Won't synchronize 

### ISSUE THREAD

**Issue by jterry21** [erwinkramer/SoundCloud-Playlist-Sync#36]
Hey man Ive been using your application for years and now for some reason it doesn't work. I recently got a new computer and it worked the first few times, but now it hasn't worked for over a week. So maybe it's just me idk.

**Comment by erwinkramer** [comment]
@jterry21 what error are you getting?

**Comment by erwinkramer** [comment]
I see we're getting a HTTP 401 back, it's not just this app. See https://github.com/ytdl-org/youtube-dl/issues/23045

**Comment by erwinkramer** [comment]
@jterry21  I'll wait and see what happens on the SoundCloud side, as of now it looks like their issue.

**Comment by jterry21** [comment]
Hey sorry for taking so long to get back too you. But it's kinda hard to explain exactly why it isn't working. It will like download one song but then after that it says "The operation was cancelled. Aggregate inner exception while downloading track" I have no idea what that means, but I have found other ways to download my playlists but there is no album art doesn't always get the artists names right yours did everything perfect until now so regardless I enjoyed your program for the time it worked I will continue to try every now and again hopefully you figure it out.

**Comment by jterry21** [comment]
I have also tried to use a different client Id, but then it says soundcloud API may be down.

**Comment by mcprat** [comment]
@erwinkramer Hey friend, whats new?
Unfortunately I'm getting the same thing. not reaching the API or using a faulty client ID gives completely different errors. How do you debug? is there a more verbose log somewhere? I can't find recent news about changes to the API but I would start there

It's been a long time since I used the app, the issue may not be recent at all

Also, when I opened the app it did not pick up that there was a new update. I am assuming that's not related, but I don't know what changes you made.

**Comment by erwinkramer** [comment]
hi @mpratt14 It's an HTTP 401 returned when trying to download. SoundCloud must have changed something but i don't know what. I also tried the **api-v2** endpoint to download tracks but the same issue persists.

**Comment by lowestprime** [comment]
same issue here

**Comment by erwinkramer** [comment]
@jterry21 , @mpratt14 , @cooperbeaman 

I've published a new version where tracks will be downloaded with the v2 endpoint. Seems to work nicely.

**Comment by jterry21** [comment]
That’s great news man ill try as soon as possible. Honestly I would pay for it if you made it that way , it’s that good of a program.

**Comment by erwinkramer** [comment]
@jterry21  i've added a PayPal donate button at the start of the readme. Enjoy the app!

**Comment by erwinkramer** [comment]
@jterry21 thank you so much for the donation, very kind of you. 

Could you maybe check out the new release (https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/tag/r14)? I've changed a bunch of stuff and i'm curious how it's working out for others.
