### ISSUE TITLE
Says API server is down

### ISSUE THREAD

**Issue by jterry21** [erwinkramer/SoundCloud-Playlist-Sync#37]
Hey,

Is anyone else able to download their playlist still? For me it says the says the soundcloud API is down so it won't let me download anything. Is this just me or is it a universal problem?

**Comment by jterry21** [comment]
I actually just re downloaded the program and thought that it would work now but instead I'm getting a different problem. When I try to download a playlist it just says the following error was thrown:system,aggregate.exception and a whole bunch of other stuff. I literally used this program less than a week ago so whatever has happened is recent.

**Comment by erwinkramer** [comment]
The client id was made invalid by SoundCloud, i've updated the default `client id 2` to a new value: `dfd268143d94dad03a4242c54646e4a4`. You can update it yourself with the new value at the `API Config` tab, or you can update the app, then remove the file `appsettings.json` at `yourDocumentsFolder\SoundCloud Playlist Sync` to make it regenerate the app settings with the new value.

**Comment by erwinkramer** [comment]
@jterry21  next time you can try and help find a working cliend id if you have nothing to do 🥇

**Comment by jterry21** [comment]
I thought maybe it would just work after a week or so but no luck. Also I tried to create a new client ID but when I click on the to create a new ID link, it doesn't load anything up. There still isn't another program like this so im hoping you can figure it out soon. Thanks anyways

**Comment by erwinkramer** [comment]
@jterry21 yes even new cliend id's i've found stopped working. I've updated the app so the link works, but you cannot register to create a new ID at the moment.

**Comment by erwinkramer** [comment]
@jterry21 i've made another change. Please update to version 27 and select `Cliend ID 2` and then press `Save settings`. This works for me, so it should work for you as well.

**Comment by jterry21** [comment]
Yeah man works perfect now appreciate your time. I just now got the chance to try out sorry for my slow response times but thanks anyways
