### ISSUE TITLE
Some playlist songs can't be synchronized

### ISSUE THREAD

**Issue by svvzo** [erwinkramer/SoundCloud-Playlist-Sync#38]
Hi,

I recently noticed that the new Soundcloud Playlist Sync is not able to synchronize all songs in my playlist anymore. For example, my playlist contains 59 tracks of which only 32 are detected. If I try to synchronize the other 27 tracks it keeps saying that all tracks are already synchronized. These are non SC-go tracks.

**Comment by erwinkramer** [comment]
@svvzo  This must be because of the new client id. At the moment i cannot make a new one and i just use one that i found online.

**Comment by erwinkramer** [comment]
@svvzo  can you post the playlist? I just checked with another one and it downloaded all just fine.

**Comment by svvzo** [comment]
Oh sorry. This is the original: https://soundcloud.com/stijnvanzoggel/sets/downl and this is the one with al tracks that won't sync: https://soundcloud.com/stijnvanzoggel/sets/dls

**Comment by erwinkramer** [comment]
I call the soundcloud API to get all the track info, if i do it with your playlist, it tells me there are no tracks at all in the playlist. So i can't do anything about it. I tried adding the tracks to another list and other client-id's, but really a SoundCloud issue...
```
{
    "duration": 8636568,
    "release_day": null,
    "permalink_url": "https://soundcloud.com/stijnvanzoggel/sets/dls",
    "genre": "",
    "permalink": "dls",
    "purchase_url": null,
    "release_month": null,
    "description": null,
    "uri": "https://api.soundcloud.com/playlists/1019821726",
    "label_name": null,
    "tag_list": "",
    "release_year": null,
    "track_count": 27,
    "user_id": 23020950,
    "last_modified": "2020/03/27 12:07:26 +0000",
    "license": "all-rights-reserved",
    "tracks": [],                                <------------- HERE
    "playlist_type": null,
    "id": 1019821726,
    "downloadable": null,
    "sharing": "public",
    "created_at": "2020/03/27 11:53:29 +0000",
    "release": null,
    "kind": "playlist",
    "title": "dls",
    "type": null,
    "purchase_title": null,
    "artwork_url": null,
    "ean": null,
    "streamable": true,
    "user": {
        "permalink_url": "https://soundcloud.com/stijnvanzoggel",
        "permalink": "stijnvanzoggel",
        "username": "stijnvanzoggel",
        "uri": "https://api.soundcloud.com/users/23020950",
        "last_modified": "2017/06/04 10:30:46 +0000",
        "id": 23020950,
        "kind": "user",
        "avatar_url": "https://i1.sndcdn.com/avatars-000049978804-6dvnvl-large.jpg"
    },
    "embeddable_by": "all",
    "label_id": null
}
```
