### ISSUE TITLE
All Playlists method Error!

### ISSUE THREAD

**Issue by lsisls** [erwinkramer/SoundCloud-Playlist-Sync#40]
I have a problem synchronizing all playlists from my profile page. Single playlists will work, but can't download them all from the first "Download Method". Every time I get the error I attached.
![Annotation 2020-04-28 180102](https://user-images.githubusercontent.com/64504137/80546019-3f587a80-897a-11ea-8bbb-ca731dca69b4.jpg)

**Comment by erwinkramer** [comment]
hi @lsisls , I just tested it, fails for you (if i test it as well) but works with my own soundcloud username. Did you recently add new playlists? I see no other option than to try and make new playlists or make a new account and see if that works (most likely).
