### ISSUE TITLE
exe wont open

### ISSUE THREAD

**Issue by RSPKM** [erwinkramer/SoundCloud-Playlist-Sync#41]
exe no longer opens, it did ask me to install  .NET Core 3.1 which i did but nothing changed.
running win 10 here.. any help would be great

**Comment by Break-Off** [comment]
Same problem here. Fresh W10 install, installed .NET Core 3.1. Exe won't open.

**Comment by erwinkramer** [comment]
Do you get any kind of notification, or what exactly happens. Also, when did it still work? It's possible that your anti-virus is blocking it, do you have anything other than Windows Defender installed?

**Comment by Break-Off** [comment]
Hey. Thanks for taking your time into this issue.

There's no warning or error whatsoever. Only indication is cursor briefly changing to wait icon and then nothing happens. No AV, just Windows Defender.

I used the application without problems 2 years ago, so I'm guessing (by looking at the release timeline) that it was around version 3.0.0.41.

**Comment by RSPKM** [comment]
thanks for the reply, just windows defender but it's not blocking (i don't think) it doesn't appear in my allow list and i don't get any notification like on other apps to allow access. 
App attempts to open but nothing happens

**Comment by erwinkramer** [comment]
Maybe try opening it as admin or disabling Windows Defender. Either way, windows Defender should give you a notification about this app being unknown, which you can accept.

**Comment by RSPKM** [comment]
hi, yes tried this.. i just get a few seconds of circle then nothing opens
defender off
open as admin

**Comment by erwinkramer** [comment]
I can reproduce this on another machine, i'll get into it. Just to be sure, you're running this .net core .exe right? `windowsdesktop-runtime-3.1.4-win-x64`

**Comment by RSPKM** [comment]
appreciate this 
I used the link supplied but it is 3.1.0 installed

**Comment by erwinkramer** [comment]
could you try downloading the 3.1.4 version from here: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.4-windows-x64-installer 

and could you show me the details screen of the exe like this: 
![image](https://user-images.githubusercontent.com/4255748/82931543-5db89280-9f87-11ea-8a20-d9b69f28f16c.png)

**Comment by Break-Off** [comment]
> 
> 
> could you try downloading the 3.1.4 version from here: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.4-windows-x64-installer

Downloaded and installed, no luck. Same behavior.

![imagen](https://user-images.githubusercontent.com/5843433/82932578-f1d72980-9f88-11ea-86ba-b39694ad6a3e.png)

**Comment by erwinkramer** [comment]
it's odd that the size of the exe doesn't match. did you try to download the latest version again from https://github.com/erwinkramer/SoundCloud-Playlist-Sync/raw/fix/Soundcloud%20Playlist%20Downloader/Releases/SoundcloudPlaylistDownloader.exe

**Comment by erwinkramer** [comment]
did you just updated the picture, lol

**Comment by Break-Off** [comment]
> 
> 
> it's odd that the size of the exe doesn't match. did you try to download the latest version again from https://github.com/erwinkramer/SoundCloud-Playlist-Sync/raw/fix/Soundcloud%20Playlist%20Downloader/Releases/SoundcloudPlaylistDownloader.exe

Sorry, that was a previous version I tried downloading (thinking it would fix the problem). It happens with latest one and that previous version.

**Comment by erwinkramer** [comment]
do you have time to chat on gitter, it's easier that way: https://gitter.im/erwinkramer/SoundCloud-Playlist-Sync?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by RSPKM** [comment]
3.1.4 Installed but so change, version same as the image

**Comment by erwinkramer** [comment]
please download the exe again as it resolves an issue

**Comment by erwinkramer** [comment]
the SoundcloudPlaylistDownloader.exe i mean

**Comment by erwinkramer** [comment]
fixed with 8afd0e01ce96861d5f2d1072c62964733f8432f7

**Comment by RSPKM** [comment]
LEGEND! thanks so much
