### ISSUE TITLE
Newtonsoft Json Error converting value {null} to type 'System.Int32' for original_content_size

### ISSUE THREAD

**Issue by giraudvalentin** [erwinkramer/SoundCloud-Playlist-Sync#42]
Hello, found a bug recently, solution work for me in local

## Problem
Newtonsoft Json Error converting value {null} to type 'System.Int32'

https://stackoverflow.com/questions/41873274/newtonsoft-json-error-converting-value-null-to-type-system-int32

![image](https://user-images.githubusercontent.com/37140584/96649531-98a1d500-1331-11eb-813f-6c9775458cea.png)

## Temporary Solution 

Work for me but not sure is the right way.
Add "?" after "int" on line 16 of SoundcloudBaseTrack.cs: 
https://github.com/erwinkramer/SoundCloud-Playlist-Sync/blob/658d1f9cd9cb498094987e57c81a991ec8c9e4d0/Soundcloud%20Playlist%20Downloader/JsonObjects/SoundcloudBaseTrack.cs#L15

`        public int? original_content_size { get; set; }
`

**Comment by erwinkramer** [comment]
@giraudvalentin yeah that's a good solution, in that same object i've made other properties nullable as well for the same problem. I'll fix that now

**Comment by erwinkramer** [comment]
changed in https://github.com/erwinkramer/SoundCloud-Playlist-Sync/commit/736b3be582e432d620a836ddddae64b1da89acc7

**Comment by erwinkramer** [comment]
I've made a new release with number 55. Can you confirm it's fixed in that one?

**Comment by giraudvalentin** [comment]
So it start to download some track but, i have another error: 

![image](https://user-images.githubusercontent.com/37140584/96771317-c6deed80-13e1-11eb-856f-ae2953aac25e.png)

**Comment by giraudvalentin** [comment]
It's possible to have url link instead text for EffectiveDownloadUrl ?

It's complicated to be copied, may be use another way ?

**Comment by erwinkramer** [comment]
Can you show me the settings you use and the playlist you download? So I can try and recreate the issue. 

The error inside is in French, it tries to copy a file to a location where it already exists? Did you change some settings?

**Comment by erwinkramer** [comment]
I changed the EffectiveDownloadUrl to the short uri and modified the File.Move behavior to be more robust. 

Can you test again in release version 57?

**Comment by giraudvalentin** [comment]
Hello,
No problem with release 58.

I cant download some songs but think it's normal, no more error on move or in the json object


```
Settings:  (lots of files ⚠️ )
Url : https://soundcloud.com/valentin-giraud/sets/
All playlists
Two Way sync
Choose high quality / convert to mp3
Replace chars by _

**Comment by erwinkramer** [comment]
@giraudvalentin i just made some more improvements to make it continue when there are a bit more songs compared to errors. Your playlists resulted in 15,3GB worth of files and just 16 not downloadable files.

**Comment by giraudvalentin** [comment]
thank you very much ;)
I tell you if I have any problem in future to fix or optimize this beautiful application :)
