### ISSUE TITLE
impossible de synchroniser

### ISSUE THREAD

**Issue by enhancer** [erwinkramer/SoundCloud-Playlist-Sync#44]
![soundcloud_playlist_error](https://user-images.githubusercontent.com/3251707/130865266-d4959bd9-46e5-4187-be23-4165a20bf8ad.PNG)

Lorsque je souhaite synchroniser , j'ai ce message d'erreur en pj. J'ai essayé les différents token fournis dans l'application mais j'ai le même message d'erreur. j'ai essayer de creer une app avec l'api soundcloud mais sur le site , il n'est plus possible demande la création d'app ( le formulaire google est bloqué).

**Comment by erwinkramer** [comment]
Please see my comment at : https://github.com/erwinkramer/SoundCloud-Playlist-Sync/issues/43#issuecomment-895483967
