### ISSUE TITLE
Playlist download method not working

### ISSUE THREAD

**Issue by noisysongbird** [erwinkramer/SoundCloud-Playlist-Sync#6]
When i try to run the set-up file, it installs into a my program files but it says installation complete and I cannot open the application.  I tried downloading the old one ver r.1.0.0.36 but when I run the application I constantly get a message saying "value cannot be null parameter name value"

**Comment by erwinkramer** [comment]
Did you try running the setup without virus scanner enabled?

Op 25 jul. 2016 6:08 p.m. schreef "noisysongbird" <notifications@github.com

**Comment by erwinkramer** [comment]
Does the error pop up without pressing any buttons in the app itself?

**Comment by noisysongbird** [comment]
Yes, I also tried running the install as administrator.  I can show you the exact error message when I get home from work.
-Noah 

    On Monday, July 25, 2016 11:10 AM, erwinkramer <notifications@github.com> wrote:
 

 Did you try running the setup without virus scanner enabled?

Op 25 jul. 2016 6:08 p.m. schreef "noisysongbird" <notifications@github.com

**Comment by erwinkramer** [comment]
Also please verify that the application updated itself to version 2.10.1.14 (you can see it at the titlebar of the app). If not, try updating it manually with the 'Update' button at the menu bar.

**Comment by noisysongbird** [comment]
The version I downloaded is r2.10.1.7 which is the only one I saw on your github.  I have attached a .txt of the error message I receieve when I try to run the setup application in the releases folder.  If there is a different version I should be installing, could you link it please? 

    On Monday, July 25, 2016 11:49 AM, erwinkramer <notifications@github.com> wrote:
 

 Also please verify that the application updated itself to version 2.10.1.14 (you can see it at the titlebar of the app). If not, try updating it manually with the 'Update' button at the menu bar.—

**Comment by erwinkramer** [comment]
I don't see your text file

**Comment by erwinkramer** [comment]
"The version I downloaded is r2.10.1.7 " That's the right version to download, however during install it auto updates to 2.10.1.14

**Comment by noisysongbird** [comment]
The attached file for the installation error is named SquirrelSetup and is a .log file but you should still be able to open it using notepad.  I have attached it to this email as well. 

    On Monday, July 25, 2016 12:31 PM, erwinkramer <notifications@github.com> wrote:
 

 "The version I downloaded is r2.10.1.7 " That's the right version to download, however during install it auto updates to 2.10.1.14—

**Comment by erwinkramer** [comment]
You can't send attachments with the way you email this message, it's not directly to me but trough GitHub. Please attach it in the chat here: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/issues/6

**Comment by noisysongbird** [comment]
My mistake, I am not that familiar with github. 


[soundcloudplaylistdownloader.txt](https://github.com/erwinkramer/SoundCloud-Playlist-Sync/files/382113/soundcloudplaylistdownloader.txt)

**Comment by erwinkramer** [comment]
Do you have Skype so we can talk there?

**Comment by noisysongbird** [comment]
I can when I get home from work.  I should be home around 5:30 PM Central time. 

    On Monday, July 25, 2016 12:50 PM, erwinkramer <notifications@github.com> wrote:
 

 Do you have Skype so we can talk there? —

**Comment by erwinkramer** [comment]
It does look like an old version, make sure you uninstall all older versions from your programs list and then run the setup from: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/download/r2.10.1.7/Soundcloud.Playlist.Sync_2_10_1_7.zip

**Comment by noisysongbird** [comment]
I was able to install this version but now I am getting an error message saying that the soundcloud API is down but I am not seeing anything on the status page. 

```
On Monday, July 25, 2016 12:52 PM, erwinkramer <notifications@github.com> wrote:
```

 It does look like an old version, make sure you uninstall all older versions from your programs list and then run the setup from: https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/download/r2.10.1.7/Soundcloud.Playlist.Sync_2_10_1_7.zip—

**Comment by noisysongbird** [comment]
I tried a few tests and I was able to download a single song at a URL but when I try to download a playlist (https://soundcloud.com/noisysongbird/sets/weird) it gives me the API message

**Comment by erwinkramer** [comment]
@noisysongbird , thanks for reporting this issue. You are right, looks like there is an issue with the download from playlist method. Every other download method seems to be working okay, could you confirm? 

Will look into this issue tonight or tomorrow.

**Comment by erwinkramer** [comment]
@noisysongbird It looks like some other playlists does work properly (for example: https://soundcloud.com/therealdossier/sets/beats-just-beats), this might point to something more problematic. Will be looking into this..

**Comment by noisysongbird** [comment]
Do you think it has something to do with the playlist URL?  I can run some tests later on today to help try to pin down the issue.

**Comment by erwinkramer** [comment]
The URL looks fine to me, if it works in the browser it should work in the app. Maybe try http instead of https

**Comment by erwinkramer** [comment]
It's a problem with SoundCloud, nothing i can do for you account playlists at the moment. It does work on other user accounts. I posted a queston [on Stackoverflow](http://stackoverflow.com/questions/38597321/soundcloud-api-users-id-playlists-not-working-with-all-users) with the hope that someone can help me out.

**Comment by noisysongbird** [comment]
Were you able to get any playlists to work?  I'm wondering if maybe changing my playlist url might do something. 

```
On Tuesday, July 26, 2016 1:29 PM, erwinkramer <notifications@github.com> wrote:
```

 It's a problem with SoundCloud, nothing i can do for you account playlists at the moment. It does work on other user accounts. I posted a queston on Stackoverflow with the hope that someone can help me out. —

**Comment by erwinkramer** [comment]
Not on your account, what the app does, is get all the playlist on an account, and then find the relevant one. However, it can't get any of your playlist. You could try renaming things and see what happens, renaming is free ;)

**Comment by noisysongbird** [comment]
I tried all of my playlists and none of them will work.  Just to test things, I tried a different playlist by an artist and it worked perfectly fine.  I also tried changing my url to noisy-songbird but that did not do anything either.

**Comment by erwinkramer** [comment]
Seems you are currently out of luck :(

**Comment by noisysongbird** [comment]
I believe the error is somehow coming from my account because I had a friend run a Downloader on my playlists and he was getting the same error message

**Comment by erwinkramer** [comment]
So i figured out how you can still download your playlist, it is kind of a work-around but it will work!

All you have to do is:
1. Find out what playlist ID your playlist has. You can see [here](http://valvepress.com/how-to-get-a-soundcloud-userplaylist-id/) how to do that at the 'For Playlists' section.
2. Create the SoundCloud URL for the app with the format: https://api.soundcloud.com/playlists/PLAYLIST_ID
3. So in your case, it would be https://api.soundcloud.com/playlists/240233014 because your playlist ID is 240233014. 
4. Paste the URL - https://api.soundcloud.com/playlists/240233014 - into the app and it just works. 

Enjoy!
