### ISSUE TITLE
The operation was canceled

### ISSUE THREAD

**Issue by Haysooooom** [erwinkramer/SoundCloud-Playlist-Sync#8]
I  had this error 
![image](https://cloud.githubusercontent.com/assets/8220471/17268984/0aa60034-563c-11e6-90b0-edbe2df5d543.png)
so what am I doing wrong?
the playlist ID thing that was mentioned in the other issue's thread did work but after a couple of songs downloaded I get this error. Any help?

**Comment by erwinkramer** [comment]
Please give me the URL you are downloading from so I can check

**Comment by Haysooooom** [comment]
https://api.soundcloud.com/playlists/179762620

**Comment by erwinkramer** [comment]
Just to be sure, you tried it again? Sometimes it just works after the second or third try. Although I expect a different issue. 

Also pretty troublesome that you also had to find out the ID manually.

**Comment by mcprat** [comment]
i bet your playlist is private. won't work if its private as the app does
not authenticate anything.

**Comment by Haysooooom** [comment]
Nah I didn't go for the first option I just saw the other guy's issue and I jut went for the playlist ID method.
Anyways I am downloading another atm and so far so good.
btw the issue I mentioned before occurred after I download a good amount of tracks like 40 or something and happened once again after a couple more

**Comment by Haysooooom** [comment]
Here is the first playlist: https://soundcloud.com/zeb-23/sets/zazz

**Comment by erwinkramer** [comment]
So it did continue and didn't get stuck on a single track, I suppose?

**Comment by Haysooooom** [comment]
It happened in the second try also but now I am downloading another playlist.

**Comment by Haysooooom** [comment]
![image](https://cloud.githubusercontent.com/assets/8220471/17269205/caa746e4-5642-11e6-9557-ff500d7639c1.png)
alright that's almost 220 songs downloaded from a single playlist. so far so good.

**Comment by erwinkramer** [comment]
The first playlist was actually https://soundcloud.com/zeb-23/sets/s0undw4v3 , will test it now

**Comment by erwinkramer** [comment]
I tried https://soundcloud.com/zeb-23/sets/zazz and it completed...

**Comment by erwinkramer** [comment]
What was the one that didn't work? https://soundcloud.com/zeb-23/sets/zazz and https://api.soundcloud.com/playlists/179762620 both work for me

**Comment by Haysooooom** [comment]
It was the one with the playlist ID but I am downloading now using the normal URL and it's going fine. Maybe it was an error cause' of multiple tracks being downloaded? I tuned it down to 1

**Comment by erwinkramer** [comment]
Well i kept it at 7 and it didn't give an error, if you happen to find a case where it consistently does error messages on a particular setting and URL then please notify me again!

Good to hear it completed, enjoy your offline collection ;) Remember that you can always sync again on the same location to have your local folder updated!

**Comment by mcprat** [comment]
I also keep concurrency on 1. a lower than average internet connection can
spawn almost random errors all the time. just need to keep resyncing

**Comment by Haysooooom** [comment]
Hopefully I don't get any errors at all but yeah my maximum download speed is 820 Kb/s so yeah it is average.
Thanks for the quick replies and great application btw.

**Comment by mcprat** [comment]
also for the less than average or even average internet it honestly is not
really faster if concurrency is greater than 1
