### ISSUE TITLE
Soundcloud API seems to be down

### ISSUE THREAD

**Issue by Haysooooom** [erwinkramer/SoundCloud-Playlist-Sync#9]
![image](https://cloud.githubusercontent.com/assets/8220471/19556137/14a3d02e-96c0-11e6-88fa-f741432a637c.png)

I keep getting this message even though I just checked the API status and it says it's working I suppose.
Any way to fix this issue?

**Comment by erwinkramer** [comment]
I am not experiencing any issues, does the error still persist?

**Comment by Haysooooom** [comment]
Everything is fine now. Probably was a common issue a couple of hours ago and they didn't mention anything about it.
